---
  - name: ensure apache is installed
    package:
      name: httpd
      state: present

  - name: ensure apache is enabled
    service:
      name: httpd
      enabled: yes

  - name: ensure apache is started
    service:
      name: httpd
      state: started

...
